version: '2'

services:
  nginx:
    image: nginx:alpine
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./public:/adserver/public:ro
    depends_on:
    - php

  php:
    image: php:fpm-alpine
    volumes:
    - .:/adserver:ro
