version: "2"

services:
  dev:
    image: adshares/adserver:dev
    build:
      context: ./docker
      dockerfile: ./dockerfile
    working_dir: /adserver
    volumes:
    - .:/adserver
    env_file:
      - docker-compose.dev.env

  queue-worker:
    image: pawzar/devops:php-fpm
    working_dir: /adserver
    volumes:
    - .:/adserver
    command: ['php','artisan','queue:work']
    user: '1000'
    restart: on-failure

  webserver:
    image: nginx:alpine
    working_dir: /adserver/public
    volumes:
    - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./public:/adserver/public

  database:
    image: mysql:8.0
    environment:
    - MYSQL_ROOT_PASSWORD=adshares
    - MYSQL_DATABASE=adserver
    - MYSQL_USER=adserver
    - MYSQL_PASSWORD=adserver

  mailer:
    image: mailhog/mailhog:latest
    user: '1000'

